name: Deploy to server
on: # Init event
  push:
    branches:
      - main

jobs:  # Define jobs
  first_job:
    runs-on: ubuntu-latest
    outputs:
      first_job_output: ${{ steps.set_output.outputs.first_job }}
    steps:
      - name: Set first job output
        id: set_output
        run: echo "job_1=First Job!" >> $GITHUB_OUTPUT
      - name: Print output variable - First Job
        run: echo "${{ steps.first_job.outputs.job_1 }}" # Access output variables from the first job


  second_job:
    needs: first_job #Create a dependency on the first job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World step
        run: echo "Hello, Second World!"
      - name: Working on Dir
        run: echo "job_2 = Second Job!" >> $GITHUB_OUTPUT # Set an output variable
      - name: Print output variable - Second Job
        run: echo "${{ steps.second_job.outputs.job_2 }}" # Access output variables from the second job

  third_job: # This job will not run if the condition if is false
    if: ${{ github.ref == 'refs/heads/main' }}  # Check if the branch is main
    needs: first_job
    runs-on: ubuntu-latest
    steps: # Two ways to create actions
      - name: Working directory
        shell: bash # Define the shell to use
        run: ls -sl
    
      - name: Working on Dir
        run: echo "job_3 = Third Job!" >> $GITHUB_OUTPUT # Set an output variable

      - name: Action
        uses: actions/checkout@v4
        with: #Define inputs or parameters
            fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Print output variable - Third Job
        run: echo "${{ steps.third_job.outputs.job_3 }}" # Access output variables from the third job
        
    #Share information between jobs
  fourth_job:
    needs: [first_job, second_job, third_job]  # Create a dependency on the first job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World step
        run: echo "Hello, Fourth World!"
      - name: Print environment variables
        run: printenv  # Print all environment variables