name: Deploy to server
on: # Init event
  push:
    branches:
      - main

jobs:  # Define jobs
  first_job:
    runs-on: ubuntu-latest
    steps: # Define steps
      - name: Hello World step
        run: echo "Hello, World!"
      - name: Worning on Dir
        run: echo "first_job = First Job!" >> $GITHUB_OUTPUT # Set an output variable


  second_job:
    needs: first_job #Create a dependency on the first job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World step
        run: echo "Hello, Second World!"
      - name: Worning on Dir
        run: echo "second_job = Second Job!" >> $GITHUB_OUTPUT # Set an output variable

  third_job: # This job will not run if the condition if is false
    if: ${{ github.ref == 'refs/heads/main' }}  # Check if the branch is main
    needs: first_job
    runs-on: ubuntu-latest
    steps: # Two ways to create actions
      - name: Working directory
        shell: bash # Define the shell to use
        run: ls -sl
    
      - name: Worning on Dir
        run: echo "third_job = Third Job!" >> $GITHUB_OUTPUT # Set an output variable

      - name: Action
        uses: actions/checkout@v4
        with: #Define inputs or parameters
            fetch-depth: 0  # Fetch all history for all branches and tags

    #Share information between jobs
  fourth_job:
    needs: [first_job, second_job, third_job]  # Create a dependency on the first job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World step
        run: echo "Hello, Fourth World!"
      - name: Print environment variables
        run: printenv  # Print all environment variables