name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      first_job_output: ${{ steps.set_output.outputs.first_job }}
    steps:
      - name: Set first job output
        id: set_output
        run: echo "first_job=First Job!" >> $GITHUB_OUTPUT
      - name: Print output variable - First Job
        run: echo "${{ steps.set_output.outputs.first_job }}"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    outputs:
      second_job_output: ${{ steps.set_job2_output.outputs.job_2 }}
    steps:
      - name: Hello World step
        run: echo "Hello, Second World!"
      - name: Working on Dir
        id: set_job2_output
        run: echo "job_2=Second Job!" >> $GITHUB_OUTPUT
      - name: Print output variable - Second Job
        run: echo "${{ steps.set_job2_output.outputs.job_2 }}"

  third_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    outputs:
      third_job_output: ${{ steps.set_job3_output.outputs.job_3 }}
    steps:
      - name: Working directory
        shell: bash
        run: ls -sl
    
      - name: Working on Dir
        id: set_job3_output
        run: echo "job_3=Third Job!" >> $GITHUB_OUTPUT

      - name: Action
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Print output variable - Third Job
        run: echo "${{ steps.set_job3_output.outputs.job_3 }}"
        
  fourth_job:
    needs: [first_job, second_job, third_job]
    runs-on: ubuntu-latest
    steps:
      - name: Hello World step
        run: echo "Hello, Fourth World!"
      - name: Print outputs from previous jobs
        run: |
          echo "First job output: ${{ needs.first_job.outputs.first_job_output }}"
          echo "Second job output: ${{ needs.second_job.outputs.second_job_output }}"
          echo "Third job output: ${{ needs.third_job.outputs.third_job_output }}"
      - name: Print environment variables
        run: printenv