name: Deploy to server
on: # Init event
  push:
    branches:
      - main

jobs:  # Define jobs
  first_job:
    runs-on: ubuntu-latest
    outputs:
      first_job_output: ${{ steps.set_output.outputs.first_job }}
    steps:
      - name: Set first job output
        id: set_output
        run: echo "first_job=First Job!" >> $GITHUB_OUTPUT

  second_job:
    needs: first_job #Create a dependency on the first job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World step
        run: echo "Hello, Second World!"
      - name: Working on Dir
        run: echo "second_job = Second Job!" >> $GITHUB_OUTPUT # Set an output variable

  third_job: # This job will not run if the condition if is false
    if: ${{ github.ref == 'refs/heads/main' }}  # Check if the branch is main
    needs: first_job
    runs-on: ubuntu-latest
    steps: # Two ways to create actions
      - name: Working directory
        shell: bash # Define the shell to use
        run: ls -sl
    
      - name: Working on Dir
        run: echo "third_job = Third Job!" >> $GITHUB_OUTPUT # Set an output variable

      - name: Action
        uses: actions/checkout@v4
        with: #Define inputs or parameters
            fetch-depth: 0  # Fetch all history for all branches and tags

    #Share information between jobs
  fourth_job:
    needs: [first_job, second_job, third_job]  # Create a dependency on the first job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World step
        run: echo "Hello, Fourth World!"
      - name: Print environment variables
        run: printenv  # Print all environment variables
      - name: Print output variable - First Job
        run: echo "first_job = ${{ needs.first_job.output.first_job }}" # Access output variables from the first job
      - name: Print output variable - Second Job
        run: echo "second_job = ${{ needs.second_job.output.second_job }}" # Access output variables from the second job
      - name: Print output variable - Third Job
        run: echo "third_job = ${{ needs.third_job.output.third_job }}" # Access output variables from the third job